const dummyLessons = [
    {
      lessonId: 1,
      courseId: 1,
      lessonName: "Introduction",
      lessonDuration: 30,
        lessonLink: "https://www.youtube.com/watch?v=PQsJR8ci3J0&ab_channel=edureka%21",
        },
    {
      lessonId: 2,
      courseId: 1,
      lessonName: "Introduction 2",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=pQN-pnXPaVg&ab_channel=freeCodeCamp.org",
    },
    {
      lessonId: 3,
      courseId: 1,
      lessonName: "Introduction 3",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=WdD0ai9cloI&ab_channel=K.K.-Topic",
    },
    {
      lessonId: 4,
      courseId: 1,
      lessonName: "Introduction 4",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=_ae2j9jZY_U&ab_channel=CLASHBOY",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
    {
      lessonId: 5,
      courseId: 1,
      lessonName: "Introduction 5",
      lessonDuration: 30,
      lessonLink: "https://www.youtube.com/watch?v=lnP76G6mr64&ab_channel=BollywoodPocketFM",
    },
  ];
   
  export { dummyLessons };